name: UI Automation with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  automation-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Java (sesuai project kamu Java 21)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3. Grant execute permission for gradlew
      - name: Grant execute permission
        run: chmod +x gradlew

      # 4. Run automation tests
      - name: Run tests
        run: ./gradlew :app:clean :app:test

      # 5. Install Allure Report
      - name: Install Allure CLI
        run: |
          ALLURE_VERSION=2.25.0
          wget https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.tgz
          tar -zxvf allure-${ALLURE_VERSION}.tgz
          sudo mv allure-${ALLURE_VERSION} /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      # 5. Generate Allure report
      - name: Generate Allure Report
        if: always()
        run: |
          allure generate app/build/allure-results \
          -o app/build/allure-report --clean

      # 6. Upload Allure report as artifact
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: app/build/allure-report

      # 7. Upload Allure report as Github Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: app/build/allure-report